import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getFirestore,collection,addDoc,query,where,orderBy,limit,onSnapshot,serverTimestamp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyA9dEr5JvvGo-xQ-6llmV6rCt_5P258YR0",authDomain:"punarasarmela.firebaseapp.com",projectId:"punarasarmela",storageBucket:"punarasarmela.firebasestorage.app",messagingSenderId:"368252030672",appId:"1:368252030672:web:531a9c3307271819e698d5",measurementId:"G-YMC3Y69L6H"};
const db=getFirestore(initializeApp(firebaseConfig)); const $=s=>document.querySelector(s);
const target=new Date('2026-09-19T00:00:00+05:30').getTime();function countdown(){const d=Math.max(0,target-Date.now());$('#days').textContent=String(Math.floor(d/86400000)).padStart(2,'0');$('#hours').textContent=String(d%86400000/3600000|0).padStart(2,'0');$('#minutes').textContent=String(d%3600000/60000|0).padStart(2,'0');$('#seconds').textContent=String(d%60000/1000|0).padStart(2,'0')}countdown();setInterval(countdown,1000);
$('#shareBtn')?.addEventListener('click',async()=>{const x={title:'पूनरासर भव्य भादवा मेला 2026',text:'19 सितम्बर 2026 • जय बाबे री 🚩',url:location.href};try{navigator.share?await navigator.share(x):window.open('https://wa.me/?text='+encodeURIComponent(x.title+'\n'+x.text+'\n'+x.url),'_blank')}catch(e){}});
$('#messageForm').addEventListener('submit',async e=>{e.preventDefault();const s=$('#status');s.textContent='संदेश भेजा जा रहा है…';try{await addDoc(collection(db,'messages'),{name:$('#name').value.trim(),text:$('#text').value.trim(),createdAt:serverTimestamp()});e.target.reset();s.textContent='संदेश सफलतापूर्वक भेज दिया गया ❤️'}catch(err){console.error(err);s.textContent='अभी संदेश नहीं भेजा जा सका।'}});
const mq=query(collection(db,'messages'),orderBy('createdAt','desc'),limit(30));onSnapshot(mq,s=>{$('#messages').innerHTML='';s.forEach(d=>{const x=d.data(),a=document.createElement('article');a.className='message';a.innerHTML='<strong>🚩 '+esc(x.name||'श्रद्धालु')+'</strong><p>'+esc(x.text||'')+'</p>';$('#messages').append(a)})},console.error);
function esc(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}function safeUrl(u){try{const x=new URL(u);return ['http:','https:'].includes(x.protocol)?x.href:'#'}catch{return '#'}}
$('#mediaForm').addEventListener('submit',async e=>{e.preventDefault();const s=$('#mediaStatus');s.textContent='शेयर भेजा जा रहा है…';try{await addDoc(collection(db,'media'),{name:$('#mediaName').value.trim(),type:$('#mediaType').value,title:$('#mediaTitle').value.trim(),url:safeUrl($('#mediaUrl').value.trim()),caption:$('#mediaCaption').value.trim(),status:'approved',createdAt:serverTimestamp()});e.target.reset();s.textContent='आपका कंटेंट शेयर हो गया ❤️'}catch(err){console.error(err);s.textContent='अभी भेजा नहीं जा सका।'}});
const aq=query(collection(db,'media'),where('status','==','approved'),orderBy('createdAt','desc'),limit(30));onSnapshot(aq,s=>{const box=$('#mediaList');box.innerHTML='';s.forEach(d=>{const x=d.data(),a=document.createElement('article');a.className='card';const icon=x.type==='video'?'🎥':x.type==='song'?'🎵':'📸';a.innerHTML='<strong>'+icon+' '+esc(x.title||'साझा कंटेंट')+'</strong><p>'+esc(x.caption||'')+'</p><div class="meta">🚩 '+esc(x.name||'श्रद्धालु')+'</div><p><a target="_blank" rel="noopener" href="'+safeUrl(x.url)+'">▶ लिंक खोलें</a></p>';box.append(a)})},()=>{});
$('#sevaForm').addEventListener('submit',async e=>{e.preventDefault();const s=$('#sevaStatus');s.textContent='सेवा जानकारी भेजी जा रही है…';try{await addDoc(collection(db,'seva'),{name:$('#sevaName').value.trim(),type:$('#sevaType').value,location:$('#sevaLocation').value.trim(),time:$('#sevaTime').value.trim(),phone:$('#sevaPhone').value.trim(),note:$('#sevaNote').value.trim(),status:'approved',createdAt:serverTimestamp()});e.target.reset();s.textContent='सेवा की जानकारी शेयर हो गई ❤️'}catch(err){console.error(err);s.textContent='अभी भेजा नहीं जा सका।'}});
const sq=query(collection(db,'seva'),where('status','==','approved'),orderBy('createdAt','desc'),limit(30));onSnapshot(sq,s=>{const box=$('#sevaList');box.innerHTML='';s.forEach(d=>{const x=d.data(),a=document.createElement('article');a.className='card';a.innerHTML='<strong>🚩 '+esc(x.name||'सेवा')+'</strong><p><b>'+esc(x.type||'')+'</b></p><p>📍 '+esc(x.location||'')+'<br>🕐 '+esc(x.time||'')+'</p><p>'+esc(x.note||'')+'</p><p><a href="tel:'+esc(x.phone||'')+'">📞 '+esc(x.phone||'संपर्क करें')+'</a></p>';box.append(a)})},()=>{});