import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getFirestore,collection,addDoc,query,where,orderBy,limit,onSnapshot,serverTimestamp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyA9dEr5JvvGo-xQ-6llmV6rCt_5P258YR0",authDomain:"punarasarmela.firebaseapp.com",projectId:"punarasarmela",storageBucket:"punarasarmela.firebasestorage.app",messagingSenderId:"368252030672",appId:"1:368252030672:web:531a9c3307271819e698d5",measurementId:"G-YMC3Y69L6H"};
const db=getFirestore(initializeApp(firebaseConfig)); const $=s=>document.querySelector(s);
const target=new Date('2026-09-24T00:00:00+05:30').getTime();function countdown(){const d=Math.max(0,target-Date.now());$('#days').textContent=String(Math.floor(d/86400000)).padStart(2,'0');$('#hours').textContent=String(d%86400000/3600000|0).padStart(2,'0');$('#minutes').textContent=String(d%3600000/60000|0).padStart(2,'0');$('#seconds').textContent=String(d%60000/1000|0).padStart(2,'0')}countdown();setInterval(countdown,1000);
$('#shareBtn')?.addEventListener('click',async()=>{const x={title:'श्री कोडमदेसर भैरूनाथ मेला 2026',text:'24–25 सितम्बर 2026 • जय श्री भैरूनाथ 🚩',url:location.href};try{navigator.share?await navigator.share(x):window.open('https://wa.me/?text='+encodeURIComponent(x.title+'\n'+x.text+'\n'+x.url),'_blank')}catch(e){}});
$('#messageForm').addEventListener('submit',async e=>{e.preventDefault();const s=$('#status');s.textContent='संदेश भेजा जा रहा है…';try{await addDoc(collection(db,'messages'),{name:$('#name').value.trim(),text:$('#text').value.trim(),createdAt:serverTimestamp()});e.target.reset();s.textContent='संदेश सफलतापूर्वक भेज दिया गया ❤️'}catch(err){console.error(err);s.textContent='अभी संदेश नहीं भेजा जा सका।'}});
const mq=query(collection(db,'messages'),orderBy('createdAt','desc'),limit(30));onSnapshot(mq,s=>{$('#messages').innerHTML='';s.forEach(d=>{const x=d.data(),a=document.createElement('article');a.className='message';a.innerHTML='<strong>🚩 '+esc(x.name||'श्रद्धालु')+'</strong><p>'+esc(x.text||'')+'</p>';$('#messages').append(a)})},console.error);
function esc(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}function safeUrl(u){try{const x=new URL(u);return ['http:','https:'].includes(x.protocol)?x.href:'#'}catch{return '#'}}
function youtubeId(raw){try{const u=new URL(raw.trim());if(u.hostname.includes('youtu.be'))return u.pathname.slice(1).split('/')[0].slice(0,11);if(u.hostname.includes('youtube.com')){if(u.pathname==='/watch')return u.searchParams.get('v')?.slice(0,11)||'';if(u.pathname.startsWith('/shorts/'))return u.pathname.split('/')[2]?.slice(0,11)||'';if(u.pathname.startsWith('/embed/'))return u.pathname.split('/')[2]?.slice(0,11)||''}}catch(e){}return ''}
let activeCat='all';let songs=[];function catLabel(c){return c==='bhajan'?'🙏 भजन':c==='padayatra'?'🚩 पदयात्रा गीत':'🪔 आरती'}
function renderSongs(){const box=$('#songsList');box.innerHTML='';const arr=songs.filter(x=>activeCat==='all'||x.category===activeCat);if(!arr.length){box.innerHTML='<div class="empty-song">अभी इस श्रेणी में कोई approved गीत नहीं है। पहला गीत आप भेजें 🎵</div>';return}arr.forEach(x=>{const a=document.createElement('article');a.className='song-card';a.innerHTML='<div><span class="song-cat">'+catLabel(x.category)+'</span><h3>'+esc(x.title||'मेला भजन')+'</h3><small>🚩 '+esc(x.name||'श्रद्धालु')+'</small></div><button class="play-song" data-id="'+esc(x.youtubeId)+'" data-title="'+esc(x.title||'मेला भजन')+'" data-cat="'+esc(catLabel(x.category))+'">▶ चलाएँ</button>';box.append(a)})}
function playSong(id,title,cat){if(!id)return;$('#nowTitle').textContent=title;$('#nowCategory').textContent=cat;$('#camelCart').classList.add('moving');$('#youtubeBox').innerHTML='<iframe src="https://www.youtube.com/embed/'+encodeURIComponent(id)+'?autoplay=1&rel=0" title="'+esc(title)+'" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>';document.querySelector('#music').scrollIntoView({behavior:'smooth',block:'start'})}
$('#musicTabs').addEventListener('click',e=>{const b=e.target.closest('button[data-cat]');if(!b)return;activeCat=b.dataset.cat;document.querySelectorAll('#musicTabs button').forEach(x=>x.classList.toggle('active',x===b));renderSongs()});
$('#songsList').addEventListener('click',e=>{const b=e.target.closest('.play-song');if(b)playSong(b.dataset.id,b.dataset.title,b.dataset.cat)});
$('#songForm').addEventListener('submit',async e=>{e.preventDefault();const s=$('#songStatus'),id=youtubeId($('#songUrl').value);s.textContent='';if(!id||id.length!==11){s.textContent='सही YouTube वीडियो लिंक डालें।';return}s.textContent='गीत approval के लिए भेजा जा रहा है…';try{await addDoc(collection(db,'songs'),{name:$('#songName').value.trim(),category:$('#songCategory').value,title:$('#songTitle').value.trim(),youtubeId:id,status:'pending',createdAt:serverTimestamp()});e.target.reset();s.textContent='गीत भेज दिया गया ❤️ Approval के बाद website पर दिखेगा।'}catch(err){console.error(err);s.textContent='अभी गीत नहीं भेजा जा सका।'}});
const sq=query(collection(db,'songs'),where('status','==','approved'),orderBy('createdAt','desc'),limit(60));onSnapshot(sq,s=>{songs=[];s.forEach(d=>songs.push(d.data()));renderSongs()},err=>{console.error('Songs:',err);$('#songsList').innerHTML='<div class="empty-song">गीत अभी लोड नहीं हो पाए।</div>'});
$('#mediaForm').addEventListener('submit',async e=>{e.preventDefault();const s=$('#mediaStatus');s.textContent='approval के लिए भेजा जा रहा है…';try{await addDoc(collection(db,'media'),{name:$('#mediaName').value.trim(),type:$('#mediaType').value,title:$('#mediaTitle').value.trim(),url:safeUrl($('#mediaUrl').value.trim()),caption:$('#mediaCaption').value.trim(),status:'pending',createdAt:serverTimestamp()});e.target.reset();s.textContent='फोटो/वीडियो भेज दिया गया ❤️ Approval के बाद public होगा।'}catch(err){console.error(err);s.textContent='अभी भेजा नहीं जा सका।'}});
const aq=query(collection(db,'media'),where('status','==','approved'),orderBy('createdAt','desc'),limit(30));onSnapshot(aq,s=>{const box=$('#mediaList');box.innerHTML='';s.forEach(d=>{const x=d.data(),a=document.createElement('article');a.className='card';const icon=x.type==='video'?'🎥':'📸';a.innerHTML='<strong>'+icon+' '+esc(x.title||'साझा कंटेंट')+'</strong><p>'+esc(x.caption||'')+'</p><div class="meta">🚩 '+esc(x.name||'श्रद्धालु')+'</div><p><a target="_blank" rel="noopener" href="'+safeUrl(x.url)+'">▶ लिंक खोलें</a></p>';box.append(a)})},()=>{});
$('#sevaForm').addEventListener('submit',async e=>{e.preventDefault();const s=$('#sevaStatus');s.textContent='approval के लिए भेजा जा रहा है…';try{await addDoc(collection(db,'seva'),{name:$('#sevaName').value.trim(),type:$('#sevaType').value,location:$('#sevaLocation').value.trim(),time:$('#sevaTime').value.trim(),phone:$('#sevaPhone').value.trim(),note:$('#sevaNote').value.trim(),status:'pending',createdAt:serverTimestamp()});e.target.reset();s.textContent='सेवा जानकारी भेज दी गई ❤️ Approval के बाद public होगी।'}catch(err){console.error(err);s.textContent='अभी भेजा नहीं जा सका।'}});
const svq=query(collection(db,'seva'),where('status','==','approved'),orderBy('createdAt','desc'),limit(30));onSnapshot(svq,s=>{const box=$('#sevaList');box.innerHTML='';s.forEach(d=>{const x=d.data(),a=document.createElement('article');a.className='card';a.innerHTML='<strong>🚩 '+esc(x.name||'सेवा')+'</strong><p><b>'+esc(x.type||'')+'</b></p><p>📍 '+esc(x.location||'')+'<br>🕐 '+esc(x.time||'')+'</p><p>'+esc(x.note||'')+'</p><p><a href="tel:'+esc(x.phone||'')+'">📞 '+esc(x.phone||'संपर्क करें')+'</a></p>';box.append(a)})},()=>{});
const pq=query(collection(db,'posters'),where('status','==','approved'),orderBy('createdAt','desc'),limit(12));onSnapshot(pq,s=>{const box=$('#posterList');box.innerHTML='';s.forEach(d=>{const x=d.data(),a=document.createElement('article');a.className='poster-card';a.innerHTML=(x.imageUrl?'<img loading="lazy" src="'+safeUrl(x.imageUrl)+'" alt="'+esc(x.title||'मेला पोस्टर')+'">':'')+'<div class="poster-copy"><span>'+esc(x.tag||'🚩 मेला संदेश')+'</span><h3>'+esc(x.title||'पूनरासर धाम')+'</h3><p>'+esc(x.text||'')+'</p></div>';box.append(a)})},()=>{});